/* ============================================================
   Skill Sync — Question Bank
   Each topic has 20 questions. A quiz draws 10 per attempt, so
   a learner gets two fully non-repeating attempts per topic.
   Format: { q: text, options: [4 strings], answer: index }
   ============================================================ */
const QUESTION_BANK = {
  "Python": [
    { q: "Which keyword defines a function in Python?", options: ["def", "func", "function", "define"], answer: 0 },
    { q: "What is the data type of `True`?", options: ["int", "bool", "str", "NoneType"], answer: 1 },
    { q: "How do you start a single-line comment in Python?", options: ["//", "#", "/*", "--"], answer: 1 },
    { q: "What is the output of `len(\"hello\")`?", options: ["4", "5", "6", "Error"], answer: 1 },
    { q: "Which symbols create an empty list?", options: ["()", "{}", "[]", "<>"], answer: 2 },
    { q: "Which operator raises a number to a power?", options: ["^", "**", "//", "%%"], answer: 1 },
    { q: "Which function converts a string to an integer?", options: ["str()", "int()", "float()", "chr()"], answer: 1 },
    { q: "Which loop iterates directly over a sequence?", options: ["for", "while", "do", "loop"], answer: 0 },
    { q: "Which built-in type is immutable?", options: ["list", "dict", "set", "tuple"], answer: 3 },
    { q: "What is the result of `7 // 2`?", options: ["3", "3.5", "4", "2"], answer: 0 },
    { q: "Which keyword is a do-nothing placeholder?", options: ["null", "pass", "void", "skip"], answer: 1 },
    { q: "How do you import a module named math?", options: ["include math", "import math", "using math", "require math"], answer: 1 },
    { q: "What does `range(3)` generate?", options: ["1, 2, 3", "0, 1, 2", "0, 1, 2, 3", "3"], answer: 1 },
    { q: "Which operator means 'not equal'?", options: ["<>", "!=", "=/=", "~="], answer: 1 },
    { q: "Which literal creates an empty dictionary?", options: ["[]", "()", "{}", "dict[]"], answer: 2 },
    { q: "Which function prints output to the console?", options: ["echo()", "printf()", "print()", "log()"], answer: 2 },
    { q: "What is `bool(0)`?", options: ["True", "False", "0", "None"], answer: 1 },
    { q: "Which keyword defines a class?", options: ["class", "struct", "object", "def"], answer: 0 },
    { q: "Which method adds an item to the end of a list?", options: ["add()", "append()", "push()", "insert()"], answer: 1 },
    { q: "What is the output of `\"ab\" * 2`?", options: ["ab2", "abab", "aabb", "Error"], answer: 1 },
  ],
  "JavaScript": [
    { q: "Which keyword declares a block-scoped variable?", options: ["var", "let", "int", "def"], answer: 1 },
    { q: "Which is the strict equality operator?", options: ["==", "===", "=", "!="], answer: 1 },
    { q: "How do you write a single-line comment in JavaScript?", options: ["#", "//", "<!-- -->", "--"], answer: 1 },
    { q: "Which method writes to the browser console?", options: ["print()", "echo()", "console.log()", "write()"], answer: 2 },
    { q: "What does `typeof []` return?", options: ["array", "object", "list", "undefined"], answer: 1 },
    { q: "Which function parses an integer from a string?", options: ["int()", "parseInt()", "Number.int()", "toInt()"], answer: 1 },
    { q: "Which character wraps a template literal?", options: ["'", "\"", "`", "/"], answer: 2 },
    { q: "Which keyword declares a constant?", options: ["const", "let", "final", "static"], answer: 0 },
    { q: "Which array method adds to the end?", options: ["push()", "pop()", "shift()", "add()"], answer: 0 },
    { q: "What does NaN stand for?", options: ["Null and None", "Not a Number", "New any Number", "No actual Name"], answer: 1 },
    { q: "Which keyword declares a classic function?", options: ["func", "def", "function", "fn"], answer: 2 },
    { q: "Which symbols create an object literal?", options: ["[]", "{}", "()", "<>"], answer: 1 },
    { q: "What is `Boolean(\"\")`?", options: ["true", "false", "\"\"", "undefined"], answer: 1 },
    { q: "Which is the logical AND operator?", options: ["&", "&&", "and", "||"], answer: 1 },
    { q: "Which method parses a JSON string?", options: ["JSON.stringify()", "JSON.parse()", "JSON.read()", "parse.JSON()"], answer: 1 },
    { q: "What is the value of an uninitialized variable?", options: ["null", "0", "undefined", "NaN"], answer: 2 },
    { q: "Which loop is guaranteed to run at least once?", options: ["for", "while", "do...while", "forEach"], answer: 2 },
    { q: "Which symbol introduces an arrow function?", options: ["=>", "->", "::", "fn"], answer: 0 },
    { q: "Which method removes the last element of an array?", options: ["pop()", "push()", "shift()", "slice()"], answer: 0 },
    { q: "What does `===` compare?", options: ["value only", "value and type", "type only", "reference only"], answer: 1 },
  ],
  "Web Basics (HTML & CSS)": [
    { q: "Which HTML tag is the largest heading?", options: ["<head>", "<h1>", "<h6>", "<title>"], answer: 1 },
    { q: "Which tag creates a hyperlink?", options: ["<link>", "<a>", "<href>", "<url>"], answer: 1 },
    { q: "Which CSS property changes text color?", options: ["text-color", "color", "font-color", "fgcolor"], answer: 1 },
    { q: "Which tag embeds an image?", options: ["<image>", "<img>", "<pic>", "<src>"], answer: 1 },
    { q: "Which CSS property sets the background color?", options: ["bgcolor", "background-color", "color-bg", "fill"], answer: 1 },
    { q: "Which tag defines an unordered list?", options: ["<ol>", "<ul>", "<li>", "<list>"], answer: 1 },
    { q: "Which attribute sets an image's source?", options: ["href", "link", "src", "path"], answer: 2 },
    { q: "Which CSS selector targets id 'main'?", options: [".main", "#main", "main", "*main"], answer: 1 },
    { q: "Which tag inserts a line break?", options: ["<lb>", "<br>", "<break>", "<nl>"], answer: 1 },
    { q: "Which CSS property makes text bold?", options: ["text-weight", "font-weight", "bold", "font-style"], answer: 1 },
    { q: "Which tag is a generic block container?", options: ["<span>", "<div>", "<box>", "<frame>"], answer: 1 },
    { q: "Which CSS property adds space inside the border?", options: ["margin", "padding", "spacing", "gap"], answer: 1 },
    { q: "Which tag defines a table row?", options: ["<td>", "<tr>", "<th>", "<table>"], answer: 1 },
    { q: "Which CSS property controls text size?", options: ["text-size", "font-size", "size", "font-scale"], answer: 1 },
    { q: "Which tag marks the page's top banner region?", options: ["<header>", "<head>", "<top>", "<h0>"], answer: 0 },
    { q: "Which attribute opens a link in a new tab?", options: ["target=\"_blank\"", "newtab", "open=\"new\"", "tab=\"new\""], answer: 0 },
    { q: "Which CSS unit is relative to the root font size?", options: ["px", "rem", "cm", "pt"], answer: 1 },
    { q: "Which tag creates a numbered list?", options: ["<ul>", "<ol>", "<li>", "<dl>"], answer: 1 },
    { q: "Which CSS property adds space outside an element?", options: ["padding", "margin", "border", "gap"], answer: 1 },
    { q: "Which tag embeds another HTML page?", options: ["<frame>", "<iframe>", "<embed>", "<include>"], answer: 1 },
  ],
  "General Knowledge": [
    { q: "What is the capital of France?", options: ["London", "Paris", "Berlin", "Rome"], answer: 1 },
    { q: "How many continents are there on Earth?", options: ["5", "6", "7", "8"], answer: 2 },
    { q: "Which is the largest planet in our solar system?", options: ["Earth", "Saturn", "Jupiter", "Neptune"], answer: 2 },
    { q: "What is the chemical formula for water?", options: ["CO2", "H2O", "O2", "NaCl"], answer: 1 },
    { q: "How many days are in a leap year?", options: ["365", "366", "364", "367"], answer: 1 },
    { q: "What is the main language spoken in Brazil?", options: ["Spanish", "Portuguese", "English", "French"], answer: 1 },
    { q: "Which is the largest ocean?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
    { q: "Approximately how fast does light travel (km/s)?", options: ["30,000", "300,000", "3,000", "3,000,000"], answer: 1 },
    { q: "Who wrote 'Romeo and Juliet'?", options: ["Dickens", "Shakespeare", "Tolstoy", "Twain"], answer: 1 },
    { q: "What is the smallest prime number?", options: ["0", "1", "2", "3"], answer: 2 },
    { q: "What is the currency of Japan?", options: ["Won", "Yuan", "Yen", "Ringgit"], answer: 2 },
    { q: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], answer: 1 },
    { q: "How many millimeters are in a centimeter?", options: ["10", "100", "1000", "1"], answer: 0 },
    { q: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Mercury"], answer: 1 },
    { q: "Who painted the Mona Lisa?", options: ["Van Gogh", "Da Vinci", "Picasso", "Rembrandt"], answer: 1 },
    { q: "Which gas do plants absorb from the air?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], answer: 1 },
    { q: "How many minutes are in an hour?", options: ["30", "60", "90", "100"], answer: 1 },
    { q: "What is the largest mammal?", options: ["Elephant", "Blue whale", "Giraffe", "Hippo"], answer: 1 },
    { q: "On which continent is the Sahara Desert?", options: ["Asia", "Africa", "Australia", "Europe"], answer: 1 },
    { q: "What is H2O commonly known as?", options: ["Salt", "Water", "Oxygen", "Acid"], answer: 1 },
  ],
  "AI / ML": [
    { q: "What does \"AI\" stand for?", options: ["Automated Input", "Artificial Intelligence", "Advanced Internet", "Applied Information"], answer: 1 },
    { q: "What does \"ML\" stand for?", options: ["Machine Learning", "Mainframe Logic", "Modular Language", "Managed Loading"], answer: 0 },
    { q: "Which learning type uses labelled data?", options: ["Unsupervised", "Supervised", "Reinforcement", "Clustering"], answer: 1 },
    { q: "Which learning finds patterns in unlabelled data?", options: ["Supervised", "Unsupervised", "Regression", "Classification"], answer: 1 },
    { q: "Which learning trains an agent using rewards and penalties?", options: ["Supervised", "Unsupervised", "Reinforcement", "Transfer"], answer: 2 },
    { q: "A model that fits training data too closely and fails on new data is?", options: ["Underfitting", "Overfitting", "Tuning", "Scaling"], answer: 1 },
    { q: "A model too simple to capture the data's patterns is?", options: ["Overfitting", "Underfitting", "Boosting", "Bagging"], answer: 1 },
    { q: "Which is a popular Python machine-learning library?", options: ["Flask", "scikit-learn", "Django", "Bootstrap"], answer: 1 },
    { q: "In a neural network, layers between input and output are called?", options: ["Hidden layers", "Edge layers", "Bias layers", "Loss layers"], answer: 0 },
    { q: "Predicting a category (spam vs not spam) is a ___ task.", options: ["Regression", "Classification", "Clustering", "Reduction"], answer: 1 },
    { q: "Predicting a continuous value (like price) is a ___ task.", options: ["Classification", "Regression", "Clustering", "Encoding"], answer: 1 },
    { q: "Grouping similar items without labels is called?", options: ["Clustering", "Labelling", "Regression", "Indexing"], answer: 0 },
    { q: "The data used to evaluate a trained model is the ___ set.", options: ["Training", "Test", "Bias", "Noise"], answer: 1 },
    { q: "Which metric measures the fraction of correct predictions?", options: ["Accuracy", "Latency", "Bandwidth", "Voltage"], answer: 0 },
    { q: "Which is a common neural-network activation function?", options: ["ReLU", "HTTP", "SQL", "JSON"], answer: 0 },
    { q: "Which is a deep-learning framework?", options: ["TensorFlow", "Photoshop", "Excel", "Apache"], answer: 0 },
    { q: "\"NLP\" in AI stands for?", options: ["Neural Logic Processing", "Natural Language Processing", "Network Layer Protocol", "Nested Loop Process"], answer: 1 },
    { q: "The column a model tries to predict is called the?", options: ["Feature", "Label / target", "Index", "Row"], answer: 1 },
    { q: "The algorithm that minimises error by adjusting weights is?", options: ["Gradient descent", "Binary search", "Bubble sort", "Hashing"], answer: 0 },
    { q: "GPUs are often used in ML because they are good at?", options: ["Parallel computation", "Printing", "Storage", "Cooling"], answer: 0 },
  ],
  "Cyber Security / Ethical Hacking": [
    { q: "What does a firewall primarily do?", options: ["Speeds up WiFi", "Filters network traffic", "Stores passwords", "Cools the CPU"], answer: 1 },
    { q: "Phishing is an attack that?", options: ["Overheats servers", "Tricks users into revealing information", "Encrypts your files", "Speeds up logins"], answer: 1 },
    { q: "Malware that locks your files and demands payment is?", options: ["Adware", "Ransomware", "Firewall", "Cookie"], answer: 1 },
    { q: "Which is the strongest password?", options: ["123456", "password", "Tq9$kL2!vR", "name123"], answer: 2 },
    { q: "\"VPN\" stands for?", options: ["Verified Public Node", "Virtual Private Network", "Visual Process Network", "Very Personal Number"], answer: 1 },
    { q: "Testing a system for weaknesses WITH permission is called?", options: ["Phishing", "Penetration testing", "Spamming", "Sniffing"], answer: 1 },
    { q: "Malware disguised as legitimate software is a?", options: ["Trojan", "Patch", "Firewall", "Token"], answer: 0 },
    { q: "Converting data into a coded form so only authorised people can read it is?", options: ["Compression", "Encryption", "Indexing", "Caching"], answer: 1 },
    { q: "\"2FA\" stands for?", options: ["Two-File Access", "Two-Factor Authentication", "Twice Fast Access", "Two-Form Address"], answer: 1 },
    { q: "An attack that floods a server with traffic to take it down is a?", options: ["DDoS", "DNS", "SQL", "FTP"], answer: 0 },
    { q: "A hacker who finds flaws to help fix them (with permission) is a?", options: ["Black hat", "White hat", "Script kiddie", "Phisher"], answer: 1 },
    { q: "SQL injection mainly targets?", options: ["Databases", "Printers", "Monitors", "Keyboards"], answer: 0 },
    { q: "HTTPS is safer than HTTP because it uses?", options: ["Bigger fonts", "Encryption (TLS/SSL)", "Faster cables", "More cookies"], answer: 1 },
    { q: "Manipulating people (not systems) to gain access is called?", options: ["Social engineering", "Brute force", "Encryption", "Patching"], answer: 0 },
    { q: "Keeping software updated mainly protects against?", options: ["Slow typing", "Known vulnerabilities", "Low battery", "Screen glare"], answer: 1 },
    { q: "Which tool is commonly used to capture and analyse network packets?", options: ["Wireshark", "Photoshop", "Notepad", "Zoom"], answer: 0 },
    { q: "Malware that copies itself to spread across networks is a?", options: ["Worm", "Cookie", "Cache", "Driver"], answer: 0 },
    { q: "The first phase of ethical hacking — gathering information — is called?", options: ["Reconnaissance", "Reporting", "Patching", "Logout"], answer: 0 },
    { q: "Adding a second verification step at login improves?", options: ["Battery life", "Account security", "Screen size", "Download speed"], answer: 1 },
    { q: "A 'brute force' attack tries to?", options: ["Guess passwords by trying many combinations", "Cool the server", "Compress files", "Speed up the network"], answer: 0 },
  ],
};

// Make the bank available to both the browser (window) and Node (server.js).
if (typeof module !== "undefined" && module.exports) module.exports = { QUESTION_BANK };
